### ISSUE TITLE
Update npm version for new changes.

### ISSUE THREAD

**Issue by IgnacioAbadie** [donovantc/react-native-intercom-webview#4]
@donovantc Hi, i Like this component so much, but please update the lastest version of npm for this component because i steel having problems with the react-native-loading-overlay and intercomWebView proptypes.

Thanks!

**Comment by hironarita** [comment]
@donovantc Could you push the recent pull requests that were merged to npm? Thanks!

**Comment by donovantc** [comment]
@IgnacioAbadie @hironarita I've published the latest changes to npm 👍
